Refactor original code
soft310team2/discord-watch-party-bot pull request #78
Opened 2023-09-20 08:36 UTC by klow358

Refactored the code so each type of command are in separate .py files 
e.g. all the bot commands to do with watchlist management are in one python file

Closes #74

2023-09-20 10:57 UTC, Mman755 approved these changes

2023-09-20 10:57 UTC, Mman755 commented on watchlist.json
> +{"watchlists": [{"name": "t", "media": {"q": {"status": "unwatched", "tags": []}}, "participants": []}]}
Reset the watchlist.json just so it starts from a fresh state each time :)

```suggestion
{"watchlists": []}
```

2023-09-20 10:58 UTC, Mman755 commented
Refactoring looks good, we just might need to test it out a bit more since its a pretty big refactor. Good work though, just reset the watchlist.json and should be all goods.

2023-09-20 19:56 UTC, tnai255 requested changes
Overall lgtm. I think it would have still been good to have the method descriptors in the bot.py as well because if anyone were to open just bot.py they can still quickly know what it does. Then group them and on the top of the group have a comment like "All method logic are located in ____".

2023-09-20 19:56 UTC, tnai255 commented on commands/watchlist.py
> +def watchlist_view(watchlist_name):
```suggestion

# View a specified watchlist
def watchlist_view(watchlist_name):
```

2023-09-20 19:56 UTC, tnai255 commented on watchlist.json
> +{"watchlists": [{"name": "t", "media": {"q": {"status": "in progress", "tags": []}}, "participants": []}]}
Reset watchlist
```suggestion
{"watchlists": []}
```

2023-09-21 06:50 UTC, tnai255 approved these changes
LGTM, one suggestion but upto if you want to take on board or not :))

2023-09-21 06:50 UTC, tnai255 commented on commands/media.py
>  def watchlist_choose(watchlist_name):
I personally think choose, clear, view watchlist should be in watchlist file cause they don't really need media info. But idk its okay if you think not!

2023-09-21 07:18 UTC, tnai255 commented on commands/media.py
>  def watchlist_choose(watchlist_name):
[Discussed in chat] - Decided to keep it as is since media information is being accessed.

2023-09-21 07:19 UTC, merged