Constrained random select
soft310team2/discord-watch-party-bot pull request #79
Opened 2023-09-20 11:57 UTC by xxu511

little change than the previous version. now it check whether it is the valid tags. Made all the tags visible followed by each media.

2023-09-20 13:20 UTC, tanagrams approved these changes
LGTM

2023-09-20 23:23 UTC, xxu511 commented
Close the issue #62

2023-09-21 08:49 UTC, tanagrams requested changes
Everything looks good, just empty the watchlist.json file to the default and should be good to merge

2023-09-21 08:57 UTC, tanagrams approved these changes

2023-09-21 08:58 UTC, merged